all:
	g++ test.cpp -o tests.exe
	tests.exe

clean:
	rm -f tests.exe
	rm -f configPage.html
	rm -f configurationSaved.html
	rm -f switchPage.html
	rm -f ConfigurationInvalidPASSWD.html
	rm -f ConfigurationInvalidSSID.html
	rm -f ConfigurationInvalidIP.html